version: '3'

tasks:
  # Task to update all repos
  update-repos:
    # Commands to run
    cmds:
      - echo "Updating repos..."
      #- cd /path/to/repo && git pull
      #- cd /path/to/another/repo && git pull
